# Generated by Django 5.2 on 2025-04-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentCompare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del fondo')),
                ('structure', models.CharField(choices=[('OPEN', 'Open'), ('CLOSE', 'Close')], default='CLOSE', max_length=5, verbose_name='Estructura del fondo')),
                ('institution', models.CharField(choices=[('BHD', 'bhd')], default='BHD', max_length=255, verbose_name='Nombre de la institucion')),
                ('register_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Numero de registro')),
                ('launch', models.DateField(blank=True, default='', max_length=255, verbose_name='Fecha de constitucion')),
                ('administrator', models.CharField(blank=True, default='', max_length=255, verbose_name='Administrador del fondo')),
                ('administration_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Comision por administracion')),
                ('performance_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Comision por desempeno')),
                ('early_redemption_fee', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Comision por rescate anticipado')),
                ('currency', models.CharField(choices=[('DOP', 'dop'), ('USD', 'usd'), ('EUR', 'eur')], default='DOP', verbose_name='Moneda de Inversion')),
                ('minimum_initial_investment', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Inversion Inicial Minima')),
                ('minimum_addition', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Inversion minima de adiciones')),
                ('minimum_balance', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Saldo minimo de permanencia')),
                ('current_share_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Valor de la cuota del dia')),
                ('previous_share_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Valor de la cuota del dia anterior')),
                ('fund_value', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Valor del fondo')),
                ('number_of_contributors', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Number de aportantes')),
                ('return_last_30_days', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 30 dias')),
                ('return_last_90_days', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 60 dias')),
                ('return_last_180_days', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 90 dias')),
                ('return_last_365_days', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 365 dias')),
            ],
        ),
    ]
