# Generated by Django 5.2 on 2025-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_fund_fundupdate_delete_investmentcompare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='administration_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=12, verbose_name='Comision por administracion'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='early_redemption_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=12, verbose_name='Comision por rescate anticipado'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='performance_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=12, verbose_name='Comision por desempeno'),
        ),
    ]
