# Generated by Django 5.2 on 2025-04-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_alter_fund_administration_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='minimum_initial_investment',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Inversion Inicial Minima'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='current_share_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Valor de la cuota del dia'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='fund_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Valor del fondo'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='number_of_contributors',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Number de aportantes'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='previous_share_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Valor de la cuota del dia anterior'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_180_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 90 dias'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_30_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 30 dias'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_365_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 365 dias'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_90_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=12, verbose_name='Rentabilidad de ultimos 60 dias'),
        ),
    ]
