# Generated by Django 5.2 on 2025-04-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_alter_fund_minimum_initial_investment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='administration_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=13, verbose_name='Comision por administracion'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='early_redemption_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=13, verbose_name='Comision por rescate anticipado'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='minimum_addition',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=13, verbose_name='Inversion minima de adiciones'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='minimum_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=13, verbose_name='Saldo minimo de permanencia'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='minimum_initial_investment',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Inversion Inicial Minima'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='performance_fee',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=13, verbose_name='Comision por desempeno'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='current_share_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Valor de la cuota del dia'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='fund_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Valor del fondo'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='number_of_contributors',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Number de aportantes'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='previous_share_value',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Valor de la cuota del dia anterior'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_180_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Rentabilidad de ultimos 90 dias'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_30_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Rentabilidad de ultimos 30 dias'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_365_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Rentabilidad de ultimos 365 dias'),
        ),
        migrations.AlterField(
            model_name='fundupdate',
            name='return_last_90_days',
            field=models.DecimalField(blank=True, decimal_places=8, default=None, max_digits=13, verbose_name='Rentabilidad de ultimos 60 dias'),
        ),
    ]
