# Generated by Django 5.2 on 2025-04-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_alter_fund_administration_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundupdate',
            name='fund_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=13, verbose_name='Valor del fondo'),
        ),
    ]
