# Generated by Django 5.2 on 2025-04-20 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_alter_fundupdate_fund_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
