# Generated by Django 5.2 on 2025-04-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_fundupdate_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualizacion'),
        ),
    ]
