# Generated by Django 5.2 on 2025-04-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('DOP', 'DOP'), ('USD', 'USD'), ('EUR', 'EUR')], default='DOP', max_length=3),
        ),
    ]
