# Generated by Django 5.2 on 2025-04-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_date_alter_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
